<?php

/**
 * BaseLabUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $user_type
 * @property Doctrine_Collection $LabAppointments
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method integer             getUserType()        Returns the current record's "user_type" value
 * @method Doctrine_Collection getLabAppointments() Returns the current record's "LabAppointments" collection
 * @method LabUser             setName()            Sets the current record's "name" value
 * @method LabUser             setUserType()        Sets the current record's "user_type" value
 * @method LabUser             setLabAppointments() Sets the current record's "LabAppointments" collection
 * 
 * @package    BookEquip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLabUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lab_user');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('user_type', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('LabAppointment as LabAppointments', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}