<?php

/**
 * BaseLabUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_user_id
 * @property string $first_name
 * @property string $last_name
 * @property string $cpf
 * @property string $telphone
 * @property string $celphone
 * @property sfGuardUser $User
 * 
 * @method integer     getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method string      getFirstName()        Returns the current record's "first_name" value
 * @method string      getLastName()         Returns the current record's "last_name" value
 * @method string      getCpf()              Returns the current record's "cpf" value
 * @method string      getTelphone()         Returns the current record's "telphone" value
 * @method string      getCelphone()         Returns the current record's "celphone" value
 * @method sfGuardUser getUser()             Returns the current record's "User" value
 * @method LabUser     setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method LabUser     setFirstName()        Sets the current record's "first_name" value
 * @method LabUser     setLastName()         Sets the current record's "last_name" value
 * @method LabUser     setCpf()              Sets the current record's "cpf" value
 * @method LabUser     setTelphone()         Sets the current record's "telphone" value
 * @method LabUser     setCelphone()         Sets the current record's "celphone" value
 * @method LabUser     setUser()             Sets the current record's "User" value
 * 
 * @package    BookEquip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLabUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lab_user');
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cpf', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('telphone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('celphone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}