lab_appointment:
  class: sfDoctrineRouteCollection
  options:
    model:                LabAppointment
    module:               agendamento
    prefix_path:          /agendamento
    column:               id
    with_wildcard_routes: true

lab_equipment_schedule:
  class: sfDoctrineRouteCollection
  options:
    model:                LabEquipmentSchedule
    module:               horario
    prefix_path:          /horario
    column:               id
    with_wildcard_routes: true

lab_equipment:
  class: sfDoctrineRouteCollection
  options:
    model:                LabEquipment
    module:               equipamento
    prefix_path:          /equipamento
    column:               id
    with_wildcard_routes: true

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               usuario
    prefix_path:          /usuario
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
