<?php

/**
 * LabAppointmentInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LabAppointmentInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LabAppointmentInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LabAppointmentInfo');
    }
}