<?php

/**
 * LabAppointmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LabAppointmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LabAppointmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LabAppointment');
    }
}