<?php

/**
 * LabEquipmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LabEquipmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LabEquipmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LabEquipment');
    }
}