<?php

/**
 * LabEquipmentAvailabilityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LabEquipmentAvailabilityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LabEquipmentAvailabilityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LabEquipmentAvailability');
    }
}