<?php

/**
 * LabUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LabUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LabUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LabUser');
    }
}