<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BookEquip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{

	public function getProfileFirstName() {
		return $this->getLabUser()->getFirstName();
	}

	public function getProfileLastName() {
		return $this->getLabUser()->getLastName();
	}

	public function getProfileEmailAddress() {
		return $this->getLabUser()->getEmailAddress();
	}

}